theme: jekyll-theme-cayman
title: "National Parks of California"
description: "Informative Website ."
gitorg: "https://github.com/mmaxwu/reunion"
description: "Learn about the beautiful parks of California"
google_analytics:
